version: '3'
networks: 
  database: 
    name: mysql
    driver: bridge
services:
  database:
    image: 'mysql:5.7'
    ports:
        - '${DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/data/database:/var/lib/mysql:rw
    networks:
      - database